services:
  - type: web
    name: bhookle-ai-usecases
    runtime: node
    plan: free
    buildCommand: npm install && npm rebuild
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_BUILD_FROM_SOURCE
        value: "true"
